name = "equipment-contacts-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "equipment-contacts"
database_id = "9d210ee0-682c-4007-bde1-53bb20b62226"
